name: Python Clean and Train

on: [push]

jobs:
  clean-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      - name: Clean data
        run: python ModelCleaning/cleandata.py

      - name: Train model
        run: python ModelCleaning/train_test_dataset.py
