name: tutorial1
on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: check-python-version
        run: python --version

  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: step2
        run: date

  job3:
    name: job3
    runs-on: ubuntu-latest
    steps:
      - name: placeholder step
        run: echo "This is Job 3"






