  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Print Python version
        run: python --version

      - name: Print pip version
        run: pip --version

      - name: Echo Job 1 text and date
        run: |
          echo "This is Job 1"
          date



