name: Tutorial 1 Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: echo "This is Job 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Step 3
        run: echo "This is Job 3"
