name: Tutorial 1 Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step for job1
        run: |
          echo "This is Job 1"
          date

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step for job2
        run: |
          echo "This is Job 2"
          date 

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Step for job3
        run: |
          echo "This is Job 3"
          date 

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Step for job4
        run: echo "I am job 4"

