name: Tutorial 1 Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: |
          echo "This is Job 1"
          date

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: |
          echo "This is Job 2"
          date

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: |
          echo "This is Job 3"
          date

  job4:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Job 4
        run: echo "I am job 4"


